=== eldiosx/web-anime/xml/animecategories.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="webanime">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="animes" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="animes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element name="director" type="xs:string"/>
        <xs:element name="year" type="xs:string"/>
        <xs:element name="episodes" type="xs:string"/>
        <xs:element ref="categories"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name">
    <xs:complexType mixed="true">
      <xs:attribute name="category" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="categories">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="category1"/>
        <xs:element ref="category2"/>
        <xs:element ref="category3"/>
        <xs:element ref="category4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="category1">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Seinen"/>
        <xs:enumeration value="Shonen"/>
        <xs:enumeration value="Drama"/>
        <xs:enumeration value="Gore"/>
        <xs:enumeration value="Distopic"/>
        <xs:enumeration value="Historic"/>
        <xs:enumeration value="Futurista"/>
        <xs:enumeration value="Accion"/>
        <xs:enumeration value="Terror"/>
        <xs:enumeration value=""/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="category2">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Seinen"/>
        <xs:enumeration value="Shonen"/>
        <xs:enumeration value="Drama"/>
        <xs:enumeration value="Gore"/>
        <xs:enumeration value="Distopic"/>
        <xs:enumeration value="Historic"/>
        <xs:enumeration value="Futurista"/>
        <xs:enumeration value="Accion"/>
        <xs:enumeration value="Terror"/>
        <xs:enumeration value=""/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="category3">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Seinen"/>
        <xs:enumeration value="Shonen"/>
        <xs:enumeration value="Drama"/>
        <xs:enumeration value="Gore"/>
        <xs:enumeration value="Distopic"/>
        <xs:enumeration value="Historic"/>
        <xs:enumeration value="Futurista"/>
        <xs:enumeration value="Accion"/>
        <xs:enumeration value="Terror"/>
        <xs:enumeration value=""/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="category4">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Seinen"/>
        <xs:enumeration value="Shonen"/>
        <xs:enumeration value="Drama"/>
        <xs:enumeration value="Gore"/>
        <xs:enumeration value="Distopic"/>
        <xs:enumeration value="Historic"/>
        <xs:enumeration value="Futurista"/>
        <xs:enumeration value="Accion"/>
        <xs:enumeration value="Terror"/>
        <xs:enumeration value=""/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== eldiosx/web-anime/xml/animecategories.xml
﻿<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="anime.css"
  title="cartera/Reciente" media="screen"
  type="text/css"?>
<webanime xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="animecategories.xsd">
<?xml-stylesheet type="text/xsl" href="file:/C:/Users/MEDAC/Desktop/1 DAM/Lenguaje de Marcas/Trabajo 2 T/XML/XML Web/animecategories.xsl"?>

  <animes>
       <name category="Seinen">Attack on Titan</name>
        <director>Yūichirō Hayashi</director>
        <year>2013</year>
        <episodes>87</episodes>
        <categories>
        <category1>Seinen</category1>
        <category2>Shonen</category2>
        <category3>Distopic</category3>
        <category4>Accion</category4>
       </categories>
  </animes>
  <animes>
    <name  category="Seinen">Death note</name>
        <director> Tetsurō Araki, Estudio Madhouse </director>
        <year> 2007 </year>
        <episodes>39</episodes>
        <categories>
        <category1>Seinen</category1>
        <category2>Accion</category2>
        <category3>Terror</category3>
        <category4></category4>
        </categories>
  </animes>
    <animes>
       <name category="Seinen">Inuyasha</name>
        <director>Josuka Toyotaro</director>
        <year>2004</year>
        <episodes>167</episodes>
        <categories>
        <category1>Shonen</category1>
        <category2>Historic</category2>
        <category3>Accion</category3>
        <category4></category4>
        </categories>
  </animes>
    <animes>
        <name category="Seinen">Devilman Crybaby</name>
       <director>Gō Nagai</director>
        <year>2018</year>
        <episodes>10</episodes>
       <categories>
        <category1>Seinen</category1>
        <category2>Shonen</category2>
       <category3>Gore</category3>
        <category4></category4>
       </categories>
  </animes>
    <animes>
        <name category="Seinen">Monster</name>
        <director>Masayuki Kojima, Estudio Madhouse</director>
        <year>2004</year>
        <episodes>74</episodes>
        <categories>
        <category1>Seinen</category1>
        <category2>Shonen</category2>
        <category3>Gore</category3>
        <category4></category4>
        </categories>
  </animes>
    <animes>
        <name category="Seinen">Psycho-Pass</name>
        <director>Shingo Natsume</director>
        <year>2012</year>
        <episodes>27</episodes>
        <categories>
        <category1>Accion</category1>
        <category2>Shonen</category2>
        <category3></category3>
        <category4></category4>
       </categories>
  </animes>
  <animes>
    <name category="Seinen">Kaguya Sama wa Kokurasetai: Tensai-tachi no Ren'ai Zunōsen</name>
        <director> Yukie Sugawara </director>
        <year>2019</year>
        <episodes>12</episodes>
        <categories>
        <category1>Seinen</category1>
        <category2>Drama</category2>
        <category3></category3>
        <category4></category4>
        </categories>
  </animes>
  <animes>
        <name category="Seinen">Ghost In the Shell</name>
        <director> Mamoru Oshii; Kenji Kamiyama; Kazuchika Kise </director>
        <year>1995</year>
        <episodes>62 chap+1 películas+2OVA</episodes>
        <categories>
        <category1>Seinen</category1>
        <category2>Distopic</category2>
        <category3>Accion</category3>
        <category4>Futurista</category4>
       </categories>
  </animes>
  <animes>
       <name category="Seinen">Parasyte</name>
        <director>Kenichi Shimizu</director>
        <year>2014</year>
        <episodes>24</episodes>
       <categories>
        <category1>Seinen</category1>
        <category2>Distopic</category2>
        <category3></category3>
        <category4></category4>
        </categories>
  </animes>
  <animes>
        <name category="Seinen">Serial Experiments Lain</name>
        <director> 	Ryūtarō Nakamura </director>
        <year>1998</year>
        <episodes>13</episodes>
        <categories>
        <category1>Seinen</category1>
        <category2>Distopic</category2>
        <category3>Drama</category3>
        <category4></category4>
        </categories>
  </animes>
  <animes>
        <name category="Seinen">Tokyo Ghoul</name>
        <director> Shuhei Morita </director>
        <year>2015</year>
        <episodes>12</episodes>
       <categories>
       <category1>Seinen</category1>
        <category2>Distopic</category2>
        <category3></category3>
        <category4></category4>
        </categories>
  </animes>
</webanime>
